openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -sha256 \
    -keyout local_only.key \
    -new \
    -out local_only.crt \
    -subj '/CN=localhost' \
    -extensions EXT \
    -config <(printf '[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth')
