"""
base configuration file
"""
from os.path import abspath, dirname, join
from os import environ as env

TEST_MODE = env.get('TEST_MODE') == 'True'

CORE_ROOT = dirname(abspath(__file__))
PROJECT_ROOT = dirname(CORE_ROOT)

SECRET_KEY = env['FLASK_SECRET_KEY']

# if TEST_MODE:
#     AWS_STORAGE_BUCKET_NAME = env['AWS_MOCK_STORAGE_BUCKET_NAME']
#     AWS_STORAGE_BUCKET_URL = env['AWS_MOCK_STORAGE_BUCKET_URL']
# else:
#     AWS_STORAGE_BUCKET_NAME = env['AWS_STORAGE_BUCKET_NAME']
#     AWS_STORAGE_BUCKET_URL = env['AWS_STORAGE_BUCKET_URL']

AWS_STORAGE_BUCKET_NAME = env['AWS_STORAGE_BUCKET_NAME']
AWS_STORAGE_BUCKET_URL = env['AWS_STORAGE_BUCKET_URL']

AWS_STORAGE_BUCKET_KEY = env['AWS_STORAGE_BUCKET_KEY']
AWS_ACCESS_KEY_ID = env['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = env['AWS_SECRET_ACCESS_KEY']

CDN_URL = env['CDN_URL']
DB_HOST__DEFAULT = env['DB_HOST__DEFAULT']
FLASK_SETTINGS_MODULE = env['FLASK_SETTINGS_MODULE']
PROJECT_NAME = env['PROJECT_NAME']
DB_NAME__DEFAULT = env['DB_NAME__DEFAULT']
APPLICATION_DOMAINS = env['APPLICATION_DOMAINS']
FLASK_SECRET_KEY = env['FLASK_SECRET_KEY']
AWS_STORAGE_BUCKET_KEY = env['AWS_STORAGE_BUCKET_KEY']
STATIC_URL = env['STATIC_URL']
DB_PORT__DEFAULT = env['DB_PORT__DEFAULT']
DB_ENGINE__DEFAULT = env['DB_ENGINE__DEFAULT']
FLASK_SETTINGS_FILE = env['FLASK_SETTINGS_FILE']
# Below are sensitive values which should not be in github.
ADMINS = env['ADMINS']
AWS_SECRET_ACCESS_KEY = env['AWS_SECRET_ACCESS_KEY']
AWS_ACCESS_KEY_ID = env['AWS_ACCESS_KEY_ID']
GOOGLE_CLIENT_ID = env['GOOGLE_CLIENT_ID']
GOOGLE_CLIENT_SECRET = env['GOOGLE_CLIENT_SECRET']
FLASK_DEBUG = env['FLASK_DEBUG']
# Below are values that are used for local developement
LOCAL_DIRECTORY = env['LOCAL_DIRECTORY']
